[window]
dimensions = { columns = 180, lines = 55 }
position = { x = 15, y = 45 }
padding = { x = 0, y = 0 }
dynamic_title = true
dynamic_padding = true
decorations = "full"
opacity = 0.95
blur = true
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "On" }

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"


[[keyboard.bindings]]
key = "Enter"
mods = "Control"
chars = "\u001b[13;5u"

[[keyboard.bindings]]
key = "Enter"
mods = "Alt"
chars = "\u001b[13;3u"

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001b[47;5u"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[9;5u"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u001b[127;5u"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Control"
chars = "\u001b[59;5u"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u001b[32;5u"

[[keyboard.bindings]]
key = "Slash"
mods = "Control|Shift"
chars = "\u001b[47;5u"

[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
chars = "\u001b[72;6u"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u001b[74;6u"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u001b[75;6u"

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[76;6u"
